---
## Facts
- name: Set Stack Name
  ansible.builtin.set_fact:
    stack_name: edgerouter

- name: "{{ stack_name }}: Set Stack Folder"
  ansible.builtin.set_fact:
    stack_folder: "/opt/{{ stack_name }}"

- name: "{{ stack_name }}: Set Stack Volume Folder"
  ansible.builtin.set_fact:
    stack_volume_folder: "{{ stack_folder }}/volumes"

# Ensure Folders
- name: "{{ stack_name }}: Create Folders"
  ansible.builtin.file:
    path: "{{ item }}/"
    state: directory
  loop:
    - "{{ stack_folder }}/secrets/"
    - "{{ stack_volume_folder }}/traefik/acme/"
    - "{{ stack_volume_folder }}/traefik/config/"
    - "{{ stack_volume_folder }}/traefik/logs/"
    - "{{ stack_volume_folder }}/postgres/data/"
    - "{{ stack_volume_folder }}/keycloak/"

## Secrets
- name: "{{ stack_name }}: Create Docker secret Keycloak User"
  ansible.builtin.lineinfile:
    path: "{{ stack_folder }}/secrets/keycloak_user"
    line: "{{ keycloak_user }}"
    state: present
    owner: root
    group: root
    mode: "0600"
    create: yes

- name: "{{ stack_name }}: Create Docker secret Keycloak Password"
  ansible.builtin.lineinfile:
    path: "{{ stack_folder }}/secrets/keycloak_password"
    line: "{{ keycloak_password }}"
    state: present
    owner: root
    group: root
    mode: "0600"
    create: yes

- name: "{{ stack_name }}: Create Docker secret postgres pw"
  ansible.builtin.lineinfile:
    path: "{{ stack_folder }}/secrets/keycloak_postgres_pw"
    line: "{{ keycloak_postgres_pw }}"
    state: present
    owner: root
    group: root
    mode: "0600"
    create: yes

# Compose File
- name: "{{ stack_name }}: Template Compose file"
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ stack_folder }}/docker-compose.yml"

- name: "{{ stack_name }}: Template Traefik Dynamic Config"
  ansible.builtin.template:
    src: "traefik_dynamic.yml.j2"
    dest: "{{ stack_volume_folder }}/traefik/config/dynamic_conf.yml"

## Deploy Stack
- name: Create Edge Network
  community.general.docker_network:
    name: "{{ EDGE_Network_Name }}"
    driver: bridge
  register: EDGE_Network

- name: Set Subnet as Facts
  ansible.builtin.set_fact:
    EDGE_Network_Subnet: "{{ EDGE_Network.network.IPAM.Config[0].Subnet }}"

- name: "{{ stack_name }}: Create and start Stack"
  community.general.docker_compose:
    state: present
    project_name: "{{ stack_name }}"
    project_src: "{{ stack_folder }}"
