---

## Stop and Prune All Docker Containers

- name: Get a list of all running docker containers
  docker_host_info:
    containers: True
  register: docker_info

- name: Stop all running docker containers
  docker_container:
    name: '{{ item.Names[0] | regex_replace("^/", "") }}'
    state: stopped
  loop: '{{ docker_info.containers }}'

- name: Prune everything
  community.general.docker_prune:
    containers: yes
    images: yes
    networks: yes
    volumes: yes
    builder_cache: yes