---
- name: Set timezone
  community.general.timezone:
    name: "{{ TIME_ZONE }}"

- name: Update apt cache & Install Tools
  apt:
    update_cache: yes
    cache_valid_time: 600
    pkg:
      - jq
      - net-tools
  when: ansible_os_family == 'Debian'

- name: ensure Pip Packages installed
  import_role:
    name: geerlingguy.pip
  vars:
    pip_install_packages:
      - name: docker
      - name: docker-compose
      - name: jsondiff
      - name: pyyaml

- name: ensure Docker Installed
  import_role:
    name: geerlingguy.docker
  vars:
    docker_install_compose: no #causes timeout in gerlingguy rol

- name: Ensure Docker Runs in Swarm mode # To be able to use Docker secrets
  community.general.docker_swarm:
    state: present

- name: add a vm.overcommit_memory setting at the end of the sysctl.conf
  sysctl: name=vm.overcommit_memory value=1 state=present reload=yes

- name: Prune Docker
  include_tasks: docker_cleanup.yml
  when: prune_docker
