---
- name: Set timezone
  community.general.timezone:
    name: "{{ TIME_ZONE }}"

- name: Update all packages to their latest version
  apt:
    name: "*"
    update_cache: yes
    cache_valid_time: 600
    state: latest

- name: Install Apt Packages
  apt:
    pkg:
      - jq
      - net-tools

- name: Install dnsmasq
  include_tasks: dnsmasq.yml
  when: hostname_loopback

- name: ensure Pip Packages installed
  import_role:
    name: geerlingguy.pip
  vars:
    pip_install_packages:
      - name: docker
      - name: docker-compose
      - name: jsondiff
      - name: pyyaml

- name: ensure Docker Installed
  import_role:
    name: geerlingguy.docker
  vars:
    docker_install_compose: no #causes timeout in gerlingguy rol

- name: add a vm.overcommit_memory setting at the end of the sysctl.conf
  sysctl: name=vm.overcommit_memory value=1 state=present reload=yes

- name: Ensure Domainname Loopback in in dnsmasq
  ansible.builtin.lineinfile:
    path: /etc/dnsmasq.d/dnsmasq-localLoopback.conf
    line: "address=/{{ DOMAINNAME }}/127.0.0.1"
    create: yes
  notify: restart dnsmasq

- name: Prune Docker
  include_tasks: docker_cleanup.yml
  when: prune_docker

- name: Flush handlers
  meta: flush_handlers